#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MAJOR 3
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MINOR 5
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_RELEASE 6


#define NVIDIA_VRWORKS_GRAPHICS_VERSION 3,5,6,0
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MAJOR_MINOR 3,5
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING "3.5.6.0"
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING_SHORT "3.5.6"
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING_MAJOR_MINOR "3.5"
